# Theme Settings
remote_theme: mmistakes/minimal-mistakes

# Site Settings
locale: en-US
title: Mass Effect 3 Multiplayer Randomizer
name: Christopher Tobin
description: Whether you are looking for a challenge, or just looking for a new setup, the Mass Effect 3 Random Class Generator solves all! What setup will you get?
url: https://christophertobin.github.io
baseurl: /me3-randomizer
repository: christophertobin/me3-randomizer

include: ["_pages"]

author: 
  name: Christopher Tobin
