title: The Mass Effect 3 Multiplayer Randomizer
description: Whether you are looking for a challenge, or just looking for a new setup, the Mass Effect 3 Random Class Generator solves all! What setup will you get?
theme: minima

header_pages:
 - react.html
 - angular.html
 - ember.html
 - jquery.html
 - javascript.html
