# Theme Settings
remote_theme: mmistakes/minimal-mistakes

# Site Settings
locale: en-US
title: Mass Effect 3 Multiplayer Randomizer
name: Christopher Tobin
description: Whether you are looking for a challenge, or just looking for a new setup, the Mass Effect 3 Random Class Generator solves all! What setup will you get?
url: https://christophertobin.github.io
baseurl: /me3-randomizer
repository: christophertobin/me3-randomizer

feature_row:
  - image_path: /assets/images/unsplash-gallery-image-1-th.jpg
    title: "JavaScript"
    excerpt: "Check out the randomizer in plain old vanilla JavaScript"
    url: "/javascript/"
    btn_label: "Read More"
    btn_class: "btn--inverse"
  - image_path: /assets/images/unsplash-gallery-image-1-th.jpg
    title: "React"
    excerpt: "The randomizer brought to you by the magic that is ReactJS"
    url: "/react/"
    btn_label: "Read More"
    btn_class: "btn--inverse"
  - image_path: /assets/images/unsplash-gallery-image-1-th.jpg
    title: "Angular"
    excerpt: "The Angularized version of the randomizer"
    url: "/angular/"
    btn_label: "Read More"
    btn_class: "btn--inverse"

author: 
  name: Christopher Tobin
